server:
  port: 8082

spring:
  application:
    name: spring-cloud-consumer

  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集为100%，默认为0.1，即10%

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
