server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: service-zuul

  #打开负载局衡器支持重试开关
  cloud:
    loadbalancer:
      retry:
        enabled: true

zuul:
  routes:
    api-a:                              #   api-a 自己定义得  随意填
      path: /api-a/**                  #   以/api-a/开头得请求都转发给 服务名为 a  服务
      serviceId: spring-cloud-producer
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-consumer

  retryable: true   #  是否开启重试功能





#logging:
#  config: classpath:logback-spring.xml



#zuul:
#  routes:
#    my:
#      path: /api-zuul/test1
#      url: http://localhost/8082/info1          #通过url映射
