server:
  port: 8084


eureka:
  client:
    serviceUrl:
      #  需要注册到的地址
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/swang_whh/spring-cloud-demo.git  # 配置git仓库的地址
          search-paths: /config-repo                      # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: swang321                             # git仓库的账号
          password: gjm456...                            # git仓库的密码
